### ISSUE TITLE
Problem when I run websocker.py

### ISSUE THREAD

**Issue by ghost** [BetaRavener/upy-websocket-server#2]
Hello, I upload all the files in my device and when I try to run  websocker.py from ampy command line and says FileNotFound. Also when I use the ls to see my directories I see the websocker.py

**Comment by BetaRavener** [comment]
This is a bit strange, but may be caused by multiple problems such as:
* Corrupted filesystem of ESP (will require erasing and flashing new firmware)
* Some problem with AMPY
* FileNotFound is not caused by missing `websocket.py`, but by other files missing, such as `ws_connection.py`, `ws_server.py` or the HTML page.

May I also suggest using [uPyLoader](https://github.com/BetaRavener/uPyLoader)? It has graphical interface, runs on all major platforms and has also support for WiFi transfers.

**Comment by ghost** [comment]
OK. Thanks for the advice!
